In [4]:
import pandas as pd

df = pd.read_csv('loan_prediction.csv')

In [5]:
from google.colab import files
uploaded = files.upload()

Saving loan_prediction.csv to loan_prediction (1).csv

In [6]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

**Scaled Data**

In [17]:
from sklearn.preprocessing import StandardScaler

# Separate features and target
X = df_balanced.drop('Loan_Status', axis=1)
y = df_balanced['Loan_Status']

# Apply scaling
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Scaling completed successfully")

Scaling completed successfully

**Scaled data into a Dataframe**

In [18]:
X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

X_scaled.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,-1.762067,0.544488,-1.167966,-0.693806,-0.479917,-0.336833,0.111353,-0.585010,-0.214099,0.290476,0.559078,1.372037
1,-1.756287,0.544488,0.856189,0.368938,-0.479917,-0.336833,-0.119446,-0.024970,-0.214099,0.290476,0.559078,-1.218566
2,-1.750506,0.544488,0.856189,-0.693806,-0.479917,2.968830,-0.408036,-0.585010,-0.986331,0.290476,0.559078,1.372037
3,-1.744725,0.544488,0.856189,-0.693806,2.083692,-0.336833,-0.484058,0.290703,-0.313742,0.290476,0.559078,1.372037
4,-1.738944,0.544488,-1.167966,-0.693806,-0.479917,-0.336833,0.138881,-0.585010,-0.052180,0.290476,0.559078,1.372037

In [19]:
X_scaled.describe()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
count,8.440000e+02,8.440000e+02,8.440000e+02,8.440000e+02,8.440000e+02,8.440000e+02,8.440000e+02,8.440000e+02,8.440000e+02,8.440000e+02,8.440000e+02,8.440000e+02
mean,-3.367501e-17,-1.683751e-16,-1.010250e-16,-6.314065e-17,8.418753e-18,-4.209376e-17,6.314065e-17,3.577970e-17,2.630860e-17,-4.419845e-17,8.418753e-17,-6.735002e-17
std,1.000593e+00,1.000593e+00,1.000593e+00,1.000593e+00,1.000593e+00,1.000593e+00,1.000593e+00,1.000593e+00,1.000593e+00,1.000593e+00,1.000593e+00,1.000593e+00
min,-1.762067e+00,-1.836588e+00,-1.167966e+00,-6.938056e-01,-4.799174e-01,-3.368330e-01,-9.276083e-01,-5.850102e-01,-1.696285e+00,-5.200981e+00,-2.028642e+00,-1.218566e+00
25%,-8.501433e-01,5.444878e-01,-1.167966e+00,-6.938056e-01,-4.799174e-01,-3.368330e-01,-4.303688e-01,-5.850102e-01,-5.186382e-01,2.904762e-01,3.255243e-02,-1.218566e+00
50%,3.972600e-03,5.444878e-01,8.561890e-01,-6.938056e-01,-4.799174e-01,-3.368330e-01,-2.684811e-01,-1.906050e-01,-2.140993e-01,2.904762e-01,5.590779e-01,7.673587e-02
75%,8.508625e-01,5.444878e-01,8.561890e-01,3.689383e-01,-4.799174e-01,-3.368330e-01,8.911196e-02,2.736195e-01,1.987048e-01,2.904762e-01,5.590779e-01,1.372037e+00
max,1.781574e+00,5.444878e-01,8.561890e-01,2.494426e+00,2.083692e+00,2.968830e+00,1.381183e+01,1.488926e+01,6.910359e+00,2.184082e+00,5.590779e-01,1.372037e+00

**Observations**

1. Feature scaling was performed using StandardScaler.  
2. The numerical features were standardized.
3. Scaling ensures that variables with larger values do not dominate variables with smaller values.      
4. This preprocessing step can improve model performance and training efficiency.